### ISSUE TITLE
IRIS license expired, Docker build fails

### ISSUE THREAD

**Issue by rcemper** [lscalese/objectscript-syntax-for-gitlab#3]
objectscript-syntax-for-gitlab-iris-1  |
objectscript-syntax-for-gitlab-iris-1  | Error: I**nvalid Community Edition license**, may have exceeded core li
ystem : $zu(56,2)=$Id: //iris/2021.2.0/kernel/common/src/events.c#1 $ 323 19Starting IRIS
objectscript-syntax-for-gitlab-iris-1  |
objectscript-syntax-for-gitlab-iris-1  | An error was detected during InterSystems IRIS startup.
objectscript-syntax-for-gitlab-iris-1  | ** Startup aborted **
objectscript-syntax-for-gitlab-iris-1  | [ERROR] Command "iris start IRIS quietly" exited with status 256

**Comment by lscalese** [comment]
The problem should be solved, pull the latest change and try to rebuild and run : 
```
docker-compose build --no-cache
docker-compose up
```

**Comment by rcemper** [comment]
SUPER!  works perfect.
the coloring is very impressive
THANKS for the fix!

**Comment by lscalese** [comment]
Thanks for the feedback @rcemper .  
I have to finish this project with create unit test and then pull request to "rouge".  
Unfortunately, I'm busy with other projects for a while.  It will be for later.
